1904cs-golf-ibis/rpgym

- README.md
> Overview, MVP, Stretch Goals, Group Norms and Roles added to the README

- server/auth/index.js
- server/db/models/user.js
> edited strava oauth files

- package.json
- server/auth/strava.js
- server/db/models/user.js
> fixed strava oauth

- package.json
- server/api/activities.js
- server/auth/strava.js
Can successfully pull activity data for a user. The access token needs to be passed in as an argument in the route. We will need to update the user in the database to include an access token on creation as well as update the token every time the user logs in.
As of right now, a access token is hard coded into the route.
> Chore: Strava Activities Route successfully works

- client/components/user-home.js
- server/db/models/user.js
> getting userToken

- client/components/user-home.js
- client/store/user.js
- server/api/activities.js
- server/auth/strava.js
> taking max_speed for specific user in via get route from strava api

- server/auth/strava.js
> updating user token for existing users in strava strategy

- client/components/global-ldb-users.js
- client/components/index.js
- client/components/leaderboard.js
- client/components/navbar.js
- client/components/user-home.js
- client/components/users.js
- client/routes.js
- client/store/user.js
- server/api/users.js
- server/auth/strava.js
Added leaderboard section to Navbar and client route. Refatored user reducer to have functionality to add multiple users onto state. Can successfully pull from the database and add users to the leaderboard.
Note: Trying to pull followers or friends from the Strava API will not work. We will need to create an "add friend" functionality to our app.
> Leaderboard

- client/components/battle.js
- client/components/user-home.js
- client/components/user-home.spec.js
- server/api/users.spec.js
- server/db/models/user.spec.js
> fix: changed the test spec to pass

- client/components/user-home.js
- public/style.css
> card concept

- client/data/attack.js
- client/data/defend.js
- client/data/moveSets.js
> some battle logics

- client/components/auth-form.js
> fix: deleted the login form

- client/components/global-ldb-users.js
- client/components/leaderboard/top-lvl.js
- client/components/leaderboard/top-speed.js
- server/db/models/user.js
> LeaderBoard continued

- package-lock.json
- package.json
- public/style.css
> fix: changed the website to look a little fun

- client/components/battle-messages.js
- client/socket.js
- client/store/battle.js
- server/db/models/user.js
- server/socket/index.js
Successfully moved the client side socket battle logic over to the server side socket. The battle component successfully displays updates from the database.
> Move battle logic to server side socket

- client/components/battle-messages.js
- public/style.css
> HP Energy Speed are more visible

- client/components/global-ldb-users.js
- client/socket.js
- client/store/battle.js
- client/store/user.js
- server/db/models/user.js
- server/socket/index.js
Added socket logic to the leaderboard component and both the server and client sockets that allow P1 to challenge player 2. When doing so, P1 emits a payload that is then console.logged into P2's client. This is the beginning logic that is supposed to send a modal message to P2 and connect P1 and P2 on "challenge"
> Implementing notification sockets

- client/components/arena.js
- client/components/battle-messages.js
- client/components/battle-room.js
- public/style.css
> added bars

- client/components/battle-messages.js
- public/style.css
> command cost on hover

- client/components/user-home.js
- public/style.css
> profile update

- client/components/auth-form.js
> fix: added spacing between navbar and signup/login button

- README.md
> feat: embedded project video presentation in readme file

- package-lock.json
- package.json
- server/db/db.js
> Heroku ssl update

- package-lock.json
- package.json
> chore: set sequelize version to 5.3.1

- .travis.yml
- package.json
> Heroku bundle js fix
